### ISSUE TITLE
NoneType issue upon startup

### ISSUE THREAD

**Issue by jrappen** [facelessuser/ColorHelper#106]
From console after startup:

```text
ColorHelper: 
Traceback (most recent call last):
  File "color_helper in ..\sublime3\Data\Installed Packages\ColorHelper.sublime-package", line 1334, in payload
  File "color_helper in ..\sublime3\Data\Installed Packages\ColorHelper.sublime-package", line 1070, in do_search
TypeError: int() argument must be a string or a number, not 'NoneType'
```

My setup:

```text
- Sublime Text 3156 x64 portable
- Windows 10 Pro x64 Version 1709
- ColorHelper ver.: 2.5.1
- mdpopups ver.: 3.3.1
- markdown ver.: 2.6.9
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8
```

**Comment by facelessuser** [comment]
This is a never ending problem with Sublime. If you take a look at that line, it should never return None... Yet sometime during load, it still does.

**Comment by jrappen** [comment]
closing as `¯\_(ツ)_/¯`

**Comment by facelessuser** [comment]
I will probably try to handle the None, but don't be surprised if another one pops up.
