### ISSUE TITLE
In liunx Erro

### ISSUE THREAD

**Issue by jingyuexing** [facelessuser/ColorHelper#115]
ColorHelper: 
Traceback (most recent call last):
  File "/home/chenroot/.config/sublime-text-3/Installed Packages/ColorHelper.sublime-package/color_helper.py", line 1334, in payload
    ch_preview.do_search(view, force)
  File "/home/chenroot/.config/sublime-text-3/Installed Packages/ColorHelper.sublime-package/color_helper.py", line 1200, in do_search
    rgba = RGBA(mdpopups.scope2style(view, scope)['background'])
AttributeError: 'module' object has no attribute 'scope2style'
Ubuntu
Sublime text 3

**Comment by facelessuser** [comment]
This sounds like you need to have your dependencies updated. Try running "Satisfy Dependencies". If that doesn't work, delete mdpopups from your Packages folder, and run "Satisfy Dependencies".
