### ISSUE TITLE
[ST4] Console errors on plugin load (do_search)

### ISSUE THREAD

**Issue by andremacola** [facelessuser/ColorHelper#149]
On Sublime 4 Build 4083 ColorHelper shows the log below on load. The plugin itself is working fine.

```
ColorHelper: 
Traceback (most recent call last):
  File "/Users/andremacola/Library/Application Support/Sublime Text/Installed Packages/ColorHelper.sublime-package/color_helper.py", line 1364, in payload
    ch_preview.do_search(view, force)
  File "/Users/andremacola/Library/Application Support/Sublime Text/Installed Packages/ColorHelper.sublime-package/color_helper.py", line 1095, in do_search
    old_box_height = int(settings.get('color_helper.box_height', 0))
TypeError: int() argument must be a string or a number, not 'NoneType'
```

**Comment by facelessuser** [comment]
Duplicate: https://github.com/facelessuser/ColorHelper/issues/106 and https://github.com/facelessuser/ColorHelper/issues/100
