### ISSUE TITLE
ValueError: A plugin with the name of 'hsluv' already exists or is not allowed

### ISSUE THREAD

**Issue by dportalesr** [facelessuser/ColorHelper#223]
## Description

Plugin completely stopped working after update.

ST console shows:
```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1456, in run_
    return self.run(**args)
  File "/Users/Dan/Library/Application Support/Sublime Text/Installed Packages/ColorHelper.sublime-package/ch_preview.py", line 513, in run
  File "./python3.3/functools.py", line 275, in wrapper
  File "/Users/Dan/Library/Application Support/Sublime Text/Installed Packages/ColorHelper.sublime-package/ch_util.py", line 188, in get_base_color
  File "/Users/Dan/Library/Application Support/Sublime Text/Installed Packages/ColorHelper.sublime-package/lib/coloraide/color.py", line 298, in register
ValueError: A plugin with the name of 'hsluv' already exists or is not allowed
```

## Support Info

- ST ver.: 4126
- Platform: osx
- Arch: x64
- Plugin ver.: 5.0.0
- Install via PC: True
- mdpopups ver.: 4.2.1

**Comment by facelessuser** [comment]
Did you restart the editor?

**Comment by dportalesr** [comment]
I restarted it but maybe it was **before** the update. I restarted it again and it's working fine now. Thanks!

**Comment by facelessuser** [comment]
I should note that this is in the Update message listed below. The underlying ColorAide library updated and changed and can now have the user select what color spaces a user wants to be loaded by default, but the feature requires a restart when values are changed.  If an existing Color object is still in memory, after update, which I imagine is the case, it may have HSLuv loaded from the older previous version.
