### ISSUE TITLE
Doesn't work on Sublime Text 4 Build 4189 (ST-4189)

### ISSUE THREAD

**Issue by nixtoshi** [facelessuser/ColorHelper#275]
The package doesn't work on a .CSS file on ST-4189 as you can see in the attached picture.

Computer: Macbook Pro Apple M2 Max
OS: Mac OS Sonoma 14.2.1 (23C71)

![Screenshot 2024-12-26 at 20 18 00](https://github.com/user-attachments/assets/4163283c-a9a2-430e-8805-5a44494c9b8f)

**Comment by facelessuser** [comment]
You will need to provide more information. Did you restart after installation? What syntax are you using for your CSS file, the built in syntax? Or did you install some external package? Lastly, if you have restarted after installation, are there errors in your console?

**Comment by facelessuser** [comment]
FYI, this is on the latest Sublime Text using the built-in CSS syntax:

<img width="216" alt="Screenshot 2024-12-27 at 10 44 56 AM" src="https://github.com/user-attachments/assets/241360b9-1000-447a-b62b-b9d1ecf344a7" />

**Comment by nixtoshi** [comment]
I got it working again now. By deleting ST's folder on Application Support and doing a fresh install.

I believe the issue was related to Sublime Text's auto-update, Sublime Text 4 was using the `Sublime Text 3` folder in `~/Library/Application Support/` on Mac, I think this caused an issue with the Package Manager.

I noticed another extension wasn't working too, these were the error logs for the other extension:

`startup, version: 4189 osx arm64 channel: stable
executable: /Applications/Sublime Text.app/Contents/MacOS/sublime_text
application: /Applications/Sublime Text.app
working dir: /
packages path: /Users/dalovar/Library/Application Support/Sublime Text 3/Packages
state path: /Users/dalovar/Library/Application Support/Sublime Text 3/Local
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/dalovar/Library/Application Support/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.276204
OpenGL Context Information:
  GL API Version: 4.1 Metal - 88
  GLSL Version: 4.10
  Vendor: Apple
  Renderer: Apple M2 Max
startup time: 0.388843
environment variables loaded using: /bin/zsh -l
git: using configuration from system git install
git: tracking working dir /Users/dalovar/git/bitbucket/distractions/inkaroca.com
git: tracking working dir /Users/dalovar/git/bitbucket/nixtoshi
first paint time: 0.406063
reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.colors
reloading python 3.3 plugin ayu.activation
reloading plugin Default.comment
reloading python 3.3 plugin ayu.Icons
reloading python 3.3 plugin ReverseCharacters.reverse_characters
reloading python 3.3 plugin SortBy.sortby
reloading plugin Default.convert_color_scheme
reloading python 3.3 plugin SortBy.sortbyregex
reloading python 3.3 plugin HTML-CSS-JS Prettify.HTMLPrettify
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.html_print
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.keymap
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin Package Control.plugin
reloading plugin RainbowIndent.boot
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python38/sublime_plugin.py", line 325, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.8/importlib/__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 868, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/dalovar/Library/Application Support/Sublime Text 3/Installed Packages/RainbowIndent.sublime-package/boot.py", line 15, in <module>
  File "/Users/dalovar/Library/Application Support/Sublime Text 3/Installed Packages/RainbowIndent.sublime-package/plugin/__init__.py", line 3, in <module>
  File "/Users/dalovar/Library/Application Support/Sublime Text 3/Installed Packages/RainbowIndent.sublime-package/plugin/commands/__init__.py", line 3, in <module>
  File "/Users/dalovar/Library/Application Support/Sublime Text 3/Installed Packages/RainbowIndent.sublime-package/plugin/commands/rainbow_indent_view_toggle.py", line 7, in <module>
  File "/Users/dalovar/Library/Application Support/Sublime Text 3/Installed Packages/RainbowIndent.sublime-package/plugin/listener.py", line 6, in <module>
  File "/Users/dalovar/Library/Application Support/Sublime Text 3/Installed Packages/RainbowIndent.sublime-package/plugin/helpers.py", line 6, in <module>
  File "/Users/dalovar/Library/Application Support/Sublime Text 3/Installed Packages/RainbowIndent.sublime-package/plugin/settings.py", line 8, in <module>
  File "/Users/dalovar/Library/Application Support/Sublime Text 3/Installed Packages/RainbowIndent.sublime-package/plugin/data_types.py", line 11, in <module>
ModuleNotFoundError: No module named 'typing_extensions'
plugins loaded
Package Control: Installing 2 libraries...
Package Control: The library "more-itertools" is not available for Python 3.8
Package Control: The library "typing-extensions" is not available for Python 3.8
Package Control: Skipping automatic upgrade, last run at 2024-12-26 22:47:30, next run at 2024-12-27 06:47:30 or after
`
