### ISSUE TITLE
Inlines and auto-popup not working

### ISSUE THREAD

**Issue by nkrim62** [facelessuser/ColorHelper#44]
Since the latest update I was excited to try out the inline color preview, but it doesn't seem to be working for me.  I've checked the settings, global and user, and it is set to true.  Along with that, since the update, the popup tooltip doesn't show up either.  I'm on a Mac using the latest Yosemite release with Sublime Text 3.

**Comment by facelessuser** [comment]
Can you do what i suggest here: https://forum.sublimetext.com/t/colorhelper-2-0-0/21762/8?u=facelessuser.

Please post the results here when you do.

**Comment by nkrim62** [comment]
- ST ver.: 3114
- Platform: osx
- Arch: x64
- Plugin ver.: 2.0.1
- Install via PC: True
- mdpopups ver.: 1.7.5
- markdown ver.: 2.6.6
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8

**Comment by facelessuser** [comment]
You are on a ST3 version that is too old for the inline popups.  You must be on 3118+.  Unfortunately, the old features should still work on other versions of ST3 3080+.  Do you see errors in the console?

**Comment by nkrim62** [comment]
Yes there's one, I didn't realize I was behind on sublime though, so maybe an update will fix everything up.  Here's the error anyway though.
```bash
Traceback (most recent call last):
    File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 162, in on_api_ready m.plugin_loaded()
    File "color_helper in /Users/samcreative/Library/Application Support/ Sublime Text 3/ Installed Packages/ColorHelper.sublime-package", line 1970, in plugin_loaded
    File "color_helper in /Users/samcreative/Library/Application Support/ Sublime Text 3/ Installed Packages/ColorHelper.sublime-package", line 1929, in settings_reload
    File "color_helper in /Users/samcreative/Library/Application Support/ Sublime Text 3/ Installed Packages/ColorHelper.sublime-package", line 1947, in setup_previews
AttributeError: 'module' object has no attribute 'erase_phantoms'
```

**Comment by facelessuser** [comment]
You are behind because you are not on the dev channel.  You are on the beta channel.  If you have a Sublime License, you can install the latest from the dev channel.

Anyways, I think I found the issue.

**Comment by nkrim62** [comment]
I switched the dev build and everything working great! Thanks for the help!

**Comment by facelessuser** [comment]
I made a release which should fix the beta branch.
