### ISSUE TITLE
Error on color box click

### ISSUE THREAD

**Issue by jrappen** [facelessuser/ColorHelper#96]
## Description

```text
Traceback (most recent call last):
  File "...\sublime3\sublime_plugin.py", line 812, in run_
    return self.run(edit, **args)
  File "color_helper in ...\sublime3\Data\Installed Packages\ColorHelper.sublime-package", line 983, in run
  File "color_helper in ...\sublime3\Data\Installed Packages\ColorHelper.sublime-package", line 891, in show_color_info
  File "color_helper in ...\sublime3\Data\Installed Packages\ColorHelper.sublime-package", line 553, in format_info
  File "...\sublime3\Data\Packages\mdpopups\st3\mdpopups\__init__.py", line 458, in color_box
    border_size, check_size, max_colors, alpha, border_map
  File "...\sublime3\Data\Packages\mdpopups\st3\mdpopups\colorbox.py", line 250, in color_box
    base64.b64encode(color_box_raw(*args, **kwargs)).decode('ascii')
  File "...\sublime3\Data\Packages\mdpopups\st3\mdpopups\colorbox.py", line 97, in color_box_raw
    assert height - (border_size * 2) >= 0, "Border size too big!"
AssertionError: Border size too big!
```

## Support Info

* Sublime Text Build 3152 (64bit, portable)
* Win10 Pro x64 Version 1709
* default `"dpi_scale": 1.0`, but HighDPI screen
* ColorHelper v2.5.1
* Install via PC: True
* mdpopups ver.: 3.0.2
* markdown ver.: 2.6.9
* pygments ver.: 2.1a0
* jinja2 ver.: 2.8

## Steps to Reproduce Issue

1. Open a Color Scheme (`*.tmTheme`) file.
2. Click on a color box.

**Comment by facelessuser** [comment]
What are your settings?

**Comment by jrappen** [comment]
Settings for what?

**Comment by facelessuser** [comment]
ColorHelper?

**Comment by jrappen** [comment]
User settings are non-existant, i.e. default.

**Comment by facelessuser** [comment]
Cool.  I'll check it this evening.

**Comment by facelessuser** [comment]
Ah, one more question.  Font size and font used? Do you adjust line padding by default in Sublime or just use stock?

**Comment by jrappen** [comment]
```json
//  Settings - User

    "font_face": "PragmataPro",
    "font_size": 8,
```

**Comment by jrappen** [comment]
I should mention, the font has some ligatures...

**Comment by facelessuser** [comment]
Box size is calculated by line height.  I was curious how small a font you were using. I outback need a safe minimum size.

**Comment by jrappen** [comment]
Ok, it works with `"font_size": 9`, so I can confirm that.

Using <kbd>Ctrl</kbd><kbd>-</kbd> Sublime will hit a minimum font size of 8, though.

**Comment by facelessuser** [comment]
Yeah. I don't specifically use don't size, but the line height that Sublime gives me.  I should just force a bigger size if line height is too small.

**Comment by facelessuser** [comment]
Low end of image calculation will now be capped to prevent this issue
